{"total_count": 95, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/spotify/pedalboard/issues/250", "repository_url": "https://api.github.com/repos/spotify/pedalboard", "labels_url": "https://api.github.com/repos/spotify/pedalboard/issues/250/labels{/name}", "comments_url": "https://api.github.com/repos/spotify/pedalboard/issues/250/comments", "events_url": "https://api.github.com/repos/spotify/pedalboard/issues/250/events", "html_url": "https://github.com/spotify/pedalboard/issues/250", "id": 1890669160, "node_id": "I_kwDOFttOWc5wsVJo", "number": 250, "title": "incompatible function argument in tensorflow", "user": {"login": "xinzuan", "id": 47246543, "node_id": "MDQ6VXNlcjQ3MjQ2NTQz", "avatar_url": "https://avatars.githubusercontent.com/u/47246543?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xinzuan", "html_url": "https://github.com/xinzuan", "followers_url": "https://api.github.com/users/xinzuan/followers", "following_url": "https://api.github.com/users/xinzuan/following{/other_user}", "gists_url": "https://api.github.com/users/xinzuan/gists{/gist_id}", "starred_url": "https://api.github.com/users/xinzuan/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xinzuan/subscriptions", "organizations_url": "https://api.github.com/users/xinzuan/orgs", "repos_url": "https://api.github.com/users/xinzuan/repos", "events_url": "https://api.github.com/users/xinzuan/events{/privacy}", "received_events_url": "https://api.github.com/users/xinzuan/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2023-09-11T14:39:15Z", "updated_at": "2023-09-11T14:41:58Z", "closed_at": "2023-09-11T14:41:58Z", "author_association": "NONE", "active_lock_reason": null, "body": "hi, i try to do a simple augmentation using reverb. however it raised following error:\r\n\r\n```TypeError: __call__(): incompatible function arguments. The following argument types are supported:\r\n    1. (self: pedalboard_native.Plugin, input_array: numpy.ndarray, sample_rate: float, buffer_size: int = 8192, reset: bool = True) -> numpy.ndarray[numpy.float32]\r\n    \r\nInvoked with: <Pedalboard with 1 plugin: [<pedalboard.Reverb room_size=0.5 damping=0.5 wet_level=0.33 dry_level=0.4 width=1 freeze_mode=0 at 0x55950b6924f0>]>; kwargs: samples=array([[0.0050354 , 0.01470947, 0.02227783, ..., 0.06311035, 0.06674194,\r\n        0.06939697]], dtype=float32), sample_rate=22050.0, buffer_size=8192, reset=True\r\n```\r\n\r\nI am not quite sure why it happen. I have make sure that the samples is numpy.ndarray but it keeps showing this error.\r\n\r\nHere how i use the function:\r\n\r\n```\r\naugment = Pedalboard([Reverb()])\r\naudio = augment(samples=audio.numpy(), sample_rate=float(sr))\r\n```\r\n\r\nThanks\r\n", "reactions": {"url": "https://api.github.com/repos/spotify/pedalboard/issues/250/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/spotify/pedalboard/issues/250/timeline", "performed_via_github_app": null, "state_reason": "not_planned", "score": 1.0}]}