{"total_count": 27, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/KarypisLab/METIS/issues/97", "repository_url": "https://api.github.com/repos/KarypisLab/METIS", "labels_url": "https://api.github.com/repos/KarypisLab/METIS/issues/97/labels{/name}", "comments_url": "https://api.github.com/repos/KarypisLab/METIS/issues/97/comments", "events_url": "https://api.github.com/repos/KarypisLab/METIS/issues/97/events", "html_url": "https://github.com/KarypisLab/METIS/issues/97", "id": 2612888863, "node_id": "I_kwDODo9Oxc6bvYUf", "number": 97, "title": "Bus error from running metis.part_graph in Python", "user": {"login": "jarnold360", "id": 186233520, "node_id": "U_kgDOCxmysA", "avatar_url": "https://avatars.githubusercontent.com/u/186233520?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jarnold360", "html_url": "https://github.com/jarnold360", "followers_url": "https://api.github.com/users/jarnold360/followers", "following_url": "https://api.github.com/users/jarnold360/following{/other_user}", "gists_url": "https://api.github.com/users/jarnold360/gists{/gist_id}", "starred_url": "https://api.github.com/users/jarnold360/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jarnold360/subscriptions", "organizations_url": "https://api.github.com/users/jarnold360/orgs", "repos_url": "https://api.github.com/users/jarnold360/repos", "events_url": "https://api.github.com/users/jarnold360/events{/privacy}", "received_events_url": "https://api.github.com/users/jarnold360/received_events", "type": "User", "user_view_type": "public", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2024-10-25T01:59:47Z", "updated_at": "2024-10-25T18:38:39Z", "closed_at": "2024-10-25T18:38:39Z", "author_association": "NONE", "sub_issues_summary": {"total": 0, "completed": 0, "percent_completed": 0}, "active_lock_reason": null, "body": "I am on MacOS with M3 Max, Sonoma 14.6.1.\r\n\r\nI installed following the instructions for GKlib and then METIS\r\nhttps://github.com/KarypisLab/GKlib\r\nhttps://github.com/KarypisLab/METIS\r\n\r\nthen I set the environment variables for METIS_DLL, METIS_IDXTYPEWIDTH, METIS_REALTYPEWIDTH manually in .zshrc\r\n\r\nThen I do pip install metis\r\n\r\nWith python 3.9 and 3.12, I tried:\r\n`import metis\r\nimport networkx as nx \r\n\r\nG = nx.balanced_tree(3,3)\r\n(num_edgecuts, parts) = metis.part_graph(G, nparts=5)`\r\n\r\nWhich returns:\r\n\r\n Runtime parameters:\r\n   Objective type: METIS_OBJTYPE_CUT\r\n   Coarsening type: METIS_CTYPE_SHEM\r\n   Initial partitioning type: METIS_IPTYPE_METISRB\r\n   Refinement type: METIS_RTYPE_GREEDY\r\n   Perform a 2-hop matching: No\r\n   Number of balancing constraints: 1\r\n   Number of refinement iterations: 10\r\n   Random number seed: -1\r\n   Number of partitions: 5\r\n   Number of cuts: 1\r\n   User-supplied ufactor: 30\r\n   Minimize connectivity: No\r\n   Create contigous partitions: No\r\n   Target partition weights: \r\n        0=[2.00e-01]   1=[2.00e-01]   2=[2.00e-01]   3=[2.00e-01]   4=[2.00e-01]\r\n   Allowed maximum load imbalance: 1.030 \r\n\r\n        40          0          0 [150] [        0:      40 ]\r\nzsh: bus error  python3\r\n\r\n\r\nI've tried a bunch of different variations of setting METIS_IDXTYPEWIDTH, METIS_REALTYPEWIDTH in the metis files, but I cannot get around this bus error. Is anyone else seeing this behavior? Thanks!", "reactions": {"url": "https://api.github.com/repos/KarypisLab/METIS/issues/97/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/KarypisLab/METIS/issues/97/timeline", "performed_via_github_app": null, "state_reason": "completed", "score": 1.0}]}